### ISSUE TITLE
Does not show in the themes menu

### ISSUE THREAD

**Issue by Izaic** [eliandoran/breeze-trilium#10]
I've followed the instructions to create a themes note and drag the file in, and then go into the appearance options to try setting it. I also enabled the titlebar, but I still do not see the breeze theme as an option. Perhaps it's because I'm using the flatpak?

**Comment by eliandoran** [comment]
Hi, @Izaic 

Maybe something wrong on my side, I will get back to you after work.

**Comment by eliandoran** [comment]
@Izaic , OK, so I've double checked and everything seems fine on my side.

Let's go over the steps, maybe something is different on your side:

1. Download https://github.com/eliandoran/breeze-trilium/releases/download/v0.7.0/KDE.Breeze.zip
2. Somewhere close to your root (right under the root note is a good candidate), right click -> Import into note
3. Import `KDE.Breeze.zip`
![image](https://github.com/eliandoran/breeze-trilium/assets/21236836/30112fbc-58ec-4676-be4d-d8c25801faec)
4. Make sure a note called "KDE Breeze" appears (with a hamburger icon), clicking it should reveal the entire CSS.
5. Press Ctrl+Shift+R to refresh the window.
6. Make sure you are not hoisted to any workspace, go to Options -> Appearance and look for "KDE Breeze".

If you still have issues, then it could be something related to flatpak. If this is the case, I will try to see if I can reproduce (currently not using Flatpak on my side).

**Comment by eliandoran** [comment]
Hi, @Izaic ,

Any updates?

**Comment by 1LtFord** [comment]
Had the same problem, also using flatpak. Your more detailed installation instructions in this issue solved it for me. Maybe update the readme? Because simply drag&drop the .zip file into the "Theme" note had a completely different outcome as right click -> "Import into note"

**Comment by 1LtFord** [comment]
Oh, I didn't read it correctly... onto <> into. My bad, sorry for bothering

**Comment by eliandoran** [comment]
Added a reference to the "manual" installation instructions in case someone might come across it in the future.

Feel free to reopen if you still have any issues.

**Comment by doobes** [comment]
Not having any luck on either Windows of Linux versions of Trilium.  Tried both drag and drop and direct import.
