### ISSUE TITLE
how to fold the left panel?

### ISSUE THREAD

**Issue by XeonDoer** [eliandoran/breeze-trilium#11]
Hello, thanks for your contributions, it's a wonderful work and I like it. 
But now,  I don't know kow do I fold the left panel? The original arrow disappeared

**Comment by eliandoran** [comment]
Hi, @XeonDoer .

This should be fixed in https://github.com/eliandoran/breeze-trilium/releases/tag/v0.7.1. Please check.

**Comment by XeonDoer** [comment]
It is in effect. Very thank you ! It's a beautiful work.
________________________________
发件人: Elian Doran ***@***.***>
发送时间: 2024年3月2日 0:52
收件人: eliandoran/breeze-trilium ***@***.***>
抄送: XeonDoer ***@***.***>; Mention ***@***.***>
主题: Re: [eliandoran/breeze-trilium] how to fold the left panel? (Issue #11)


Hi, @XeonDoer<https://github.com/XeonDoer> .

This should be fixed in https://github.com/eliandoran/breeze-trilium/releases/tag/v0.7.1. Please check.

―
