### ISSUE TITLE
The background color of the dropdown menu changes to solid white, which makes the text invisible

### ISSUE THREAD

**Issue by hoshiki** [eliandoran/breeze-trilium#13]
When using a dropdown menu to select content, the background changes to a solid white color. 
![image](https://github.com/eliandoran/breeze-trilium/assets/11765501/b8e2553c-2671-4fdc-a87e-53c1e9388137)

After checking, the style 
![image](https://github.com/eliandoran/breeze-trilium/assets/11765501/edc7706d-540b-4384-b75d-acc8d4f84168) 
![image](https://github.com/eliandoran/breeze-trilium/assets/11765501/3142d5d7-1019-497c-93cb-62faaf26e2ff)

 in selector ".btn:not(.search-button), select.form-control" overriders the style 
![image](https://github.com/eliandoran/breeze-trilium/assets/11765501/315db16c-c7d7-4632-8a93-6cfcb951f82b)
![image](https://github.com/eliandoran/breeze-trilium/assets/11765501/d103c43d-4e08-4554-9205-0624e498449f)

in selector ".form-control"
Is this a configuration issue or a design issue,How should I fix it? :-)

**Comment by eliandoran** [comment]
Hi, @hoshiki .

Weirdly enough I had a fix for it already in #4, but somehow I managed not to release it.

It should be OK now with this release: https://github.com/eliandoran/breeze-trilium/releases/tag/v0.7.2

Let me know your thoughts.
