### ISSUE TITLE
Regarding the contrast issue between the background color and text color within buttons.

### ISSUE THREAD

**Issue by Richard-M-L** [eliandoran/breeze-trilium#14]
# Hello, I'm a Chinese user who has been helped by your project. Therefore, my question is for ChatGPT to translate, and there may be some linguistic nuances. First of all, I want to thank you for making my note interface more beautiful and concise.
## Here are two images of my questions below:
![1713411686440](https://github.com/eliandoran/breeze-trilium/assets/92711041/33069596-489f-42e5-81b7-3a590c7eace3)
![1713411717124](https://github.com/eliandoran/breeze-trilium/assets/92711041/808df68a-1d94-4cc6-b7b6-f61db3e0d1a5)
## Here is the description of my question:
When using the application, I noticed that the contrast between the background color and text color of some buttons is insufficient, which affects the usability of the buttons. The two interactive buttons I am aware of are the confirmation button for deleting notes and the save button for setting the left-hand note directory. I have attempted to make changes based on my basic understanding of CSS, but I haven't been able to locate the code that addresses this issue. The code snippet I found can change the background color of the buttons, but I couldn't find the code to change the text color within the buttons, which results in the changes not being aesthetically pleasing.
> select.form-control {
  font-size:var(--tree-font-size);
  border: 1px solid var(--breeze-button-border) !important;
  border-radius: 3px !important;
  padding: 6px 10px !important;
  background: linear-gradient(to bottom, var(--breeze-button-background-start), var(--breeze-button-background-end)) !important;
  cursor: default !important;
  transition: border-color var(--breeze-transition-fast);
  box-shadow: 0 1px 0 var(--breeze-button-shadow);

**Comment by eliandoran** [comment]
Hello, @Richard-M-L .

Seems that some of the buttons (called primary buttons) had a white color that I did not change from the original theme. I have made a fix and would like you to test it. You can download the .css file here: https://github.com/eliandoran/breeze-trilium/actions/runs/8763291035/artifacts/1431703077 you'd need to extract the zip file and copy-paste the content of the theme into your Breeze theme note.

Let me know if you need any help or if you find any other issues.
